clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0
      tags: true

steps:
  publish-image:
    image: woodpeckerci/plugin-docker-buildx
    when:
      - event: [push, tag, manual]
    settings:
      registry: ghcr.io
      repo: ghcr.io/st7105/ghcr-cleaning-action
      dockerfile: Dockerfile
      platforms: linux/amd64
      provenance: false
      tags:
        - latest
        - main
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      cache_from:
        - ghcr.io/st7105/ghcr-cleaning-action:latest

  check-token-scopes:
    image: curlimages/curl:8.10.1
    when:
      - event: manual
    environment:
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - curl -sI -H "Authorization: Bearer $GHCR_TOKEN" https://api.github.com/user | grep -i x-oauth-scopes
